[Settings]
  ID = "368b7e0c-f54f-4e20-b761-6f639969584e"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
# This is the directory that you are publishing from (relative to root of your repo)
  publish = "dist/"
# This will be your default build command
  command = "ember build"

[build.environment]
  NODE_VERSION = "20"
  RUBY_VERSION = "2.7.6"

# Production context: All deploys from the Production branch set in your site's deploy settings will inherit these settings.
[context.production]
  command = "ember build -e production"

# Deploy Preview context: All Deploy Previews (https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
# will inherit these settings.
[context.deploy-preview]
  command = "ember build"

# Branch Deploy context: All deploys that are not resulting from a Pull/Merge Request and not from the primary, linked branch will inherit these settings.
[context.branch-deploy]
  command = "ember build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
