name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  # Disable tests until they can be all fixed
  # test:
  #   name: "Test"
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.x
  #         cache: npm
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Run Tests
  #       run: npm test
